# Generated by Django 3.1.4 on 2021-03-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateField()),
                ('filter_enum', models.CharField(choices=[('Bebida', 'B'), ('Estilo', 'E'), ('Instalacion', 'I'), ('Ocio', 'O'), ('Tapa', 'T')], max_length=25)),
                ('type_text', models.CharField(max_length=100)),
                ('value_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
