# Generated by Django 3.1.4 on 2021-04-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counter',
            new_name='Ranking',
        ),
    ]
