# Generated by Django 3.1.4 on 2021-03-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counters',
            new_name='Counter',
        ),
    ]
