# Generated by Django 3.1.4 on 2021-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210402_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='filter_enum',
            field=models.CharField(choices=[('Ambiente', 'A'), ('Bebida', 'B'), ('Estilo', 'E'), ('Instalacion', 'I'), ('Ocio', 'O'), ('Tapa', 'T')], max_length=25),
        ),
    ]
