# Generated by Django 3.1.4 on 2021-04-02 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210324_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='value_number',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
