language: python 
python: 
- "3.9"
env: 
- DJANGO=3.1.7 DB=sqlite
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd barTrenderBackEnd
  - coverage run --branch --source=. ./manage.py test --keepdb
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  - provider: heroku
  - strategy: git
  - api_key: $HEROKU_API_KEY
  - app: 
    - develop: https://bartrender-back-dev-s1.herokuapp.com/	
    - on:
      - branch: develop
