# Generated by Django 3.1.7 on 2021-03-18 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100)),
                ('cif_text', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='It does not match with CIF pattern.', regex='^[a-zA-Z]{1}\\d{7}[a-zA-Z0-9]{1}$')])),
                ('phone_number', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='There have to be 9 numbers.', regex='^\\d{9}$')])),
                ('zone_enum', models.CharField(choices=[('Alameda', 'Al'), ('Triana', 'Tr'), ('Macarena', 'Mc'), ('Remedios', 'Rm'), ('Bermejales', 'B'), ('Cartuja', 'C'), ('Nervion', 'N'), ('San Bernardo', 'Sb'), ('Sevilla Este', 'Se'), ('Bellavista', 'Be'), ('Exterior', 'Ex')], max_length=25)),
                ('verified_bool', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.owner')),
            ],
        ),
    ]
