# Generated by Django 3.1.7 on 2021-03-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_establishment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_enum', models.CharField(choices=[('Bebida', 'B'), ('Estilo', 'E'), ('Instalación', 'I'), ('Ocio', 'O'), ('Tapa', 'T')], max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='tags',
            field=models.ManyToManyField(to='authentication.Tag'),
        ),
    ]
