# Generated by Django 3.1.4 on 2021-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='premium_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('Ambiente', 'A'), ('Bebida', 'B'), ('Estilo', 'E'), ('Instalacion', 'I'), ('Ocio', 'O'), ('Tapa', 'T')], max_length=25),
        ),
    ]
