# Generated by Django 3.1.4 on 2021-03-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='user_id',
            field=models.ManyToManyField(to='authentication.Client'),
        ),
    ]
