# Generated by Django 3.1.4 on 2021-04-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_auto_20210408_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='desc_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
