# Generated by Django 3.1.4 on 2021-03-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_discount_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='user_id',
            new_name='clients_id',
        ),
    ]
