# Generated by Django 3.1.4 on 2021-03-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('establishments', '0003_auto_20210318_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='clients_id',
            field=models.ManyToManyField(blank=True, null=True, to='authentication.Client'),
        ),
    ]
