# Generated by Django 3.1.4 on 2021-03-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0005_auto_20210318_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='initial_date',
            field=models.DateTimeField(),
        ),
    ]
